### ISSUE TITLE
Run Graphdb as different user then root

### ISSUE THREAD

**Issue by phlegx** [Ontotext-AD/graphdb-docker#5]
Would be nice to have Graphdb running as a different user then root. This is best practice.

**Comment by stefanbischof** [comment]
I'm currently creating my own Docker image with this simple Dockerfile (`tag` is a build argument which has to be set when running `docker build`):

```Dockerfile
FROM ontotext/graphdb:${tag}

RUN chown -R nobody /opt/graphdb
USER nobody
```

Maybe the `USER` command could be easily integrated into the official Dockerfile? Then we wouldn't need the `chown` shell command anymore.

**Comment by ThomasThelen** [comment]
+1 for this, especially since it's common for people to expose sparql endpoints to the open world. This opens up a direct route to a service in the container with elevated privs

**Comment by bkis** [comment]
If you're using `docker compose`, it seems to work to do the following:

```yml
services:
  graphdb:
    image: "ontotext/graphdb:${WHATEVER_VERSION_YOU_USE}"
    volumes:
      - "./data:/opt/graphdb/home"
    user: 2222:2222
    # ...
```

... and chown `./data` to `2222:2222`, of course.
